<!-- Menu Déroulant -->
<html>
<?php
        $lien = '..\page.connexion\formulaireConnexion.php';
        if($_SESSION['estMedecin'])
            $lien = '..\page.medecin\accueil.php';
        else
            $lien = '..\page.patient\acceuil.php';
?>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href=".\menu_deroulant.css" media="all"/>
</head>

<body>
	<nav>
		<label for="menu-mobile" class="menu-mobile">Menu</label>
		<input type="checkbox" id="menu-mobile" role="button">
		<img src="../logoSite.ico" alt="Logo medecin patient" class="bloc1"/>
		<ul class="bloc2">
			<li class='acceuil'><a href="#">Accueil</a></li>
			<li class='rechercher'><a href='#'>Rechercher</a></li>
			<li class="compte"><a href="#">Mon compte</a></li>
			<li class="creneau"> <a href="#">Ajouter un créneau</a></li>
		</ul>	
	</nav>
</br>
</body>
<html>
	<!-- Fin Menu deroulant  -->